INSERT INTO users (email, first_name, last_name, password, created_at) VALUES('matias.gualino@gmail.com', 'Matias', 'Gualino', 'paw', current_timestamp);
INSERT INTO users (email, first_name, last_name, password, created_at) VALUES('alejandro@gmail.com', 'Alejandro', 'Bezdjian', 'paw', current_timestamp);
INSERT INTO users (email, first_name, last_name, password, created_at) VALUES('damian@gmail.com', 'Damian', 'Rizzotto', 'paw', current_timestamp);
INSERT INTO users (email, first_name, last_name, password, created_at) VALUES('mauricio@gmail.com', 'Mauricio', 'Minestrelli', 'paw', current_timestamp);

INSERT INTO job_offers (title, description, user_id, created_at) VALUES('Oferta prueba 1', 'Esto es una prueba', 1, current_timestamp);
INSERT INTO job_offers (title, description, user_id, created_at) VALUES('Oferta prueba 2', 'Esto es una prueba', 1, current_timestamp);
INSERT INTO job_offers (title, description, user_id, created_at) VALUES('Oferta prueba 1', 'Esto es una prueba', 2, current_timestamp);
INSERT INTO job_offers (title, description, user_id, created_at) VALUES('Oferta prueba 2', 'Esto es una prueba', 2, current_timestamp);
INSERT INTO job_offers (title, description, user_id, created_at) VALUES('Oferta prueba 1', 'Esto es una prueba', 3, current_timestamp);
INSERT INTO job_offers (title, description, user_id, created_at) VALUES('Oferta prueba 2', 'Esto es una prueba', 3, current_timestamp);
INSERT INTO job_offers (title, description, user_id, created_at) VALUES('Oferta prueba 1', 'Esto es una prueba', 4, current_timestamp);
INSERT INTO job_offers (title, description, user_id, created_at) VALUES('Oferta prueba 2', 'Esto es una prueba', 4, current_timestamp);

INSERT INTO posts (title, description, user_id, created_at) VALUES('Post prueba 1', 'Esto es una prueba', 1, current_timestamp);
INSERT INTO posts (title, description, user_id, created_at) VALUES('Post prueba 2', 'Esto es una prueba', 1, current_timestamp);
INSERT INTO posts (title, description, user_id, created_at) VALUES('Post prueba 1', 'Esto es una prueba', 2, current_timestamp);
INSERT INTO posts (title, description, user_id, created_at) VALUES('Post prueba 2', 'Esto es una prueba', 2, current_timestamp);
INSERT INTO posts (title, description, user_id, created_at) VALUES('Post prueba 1', 'Esto es una prueba', 3, current_timestamp);
INSERT INTO posts (title, description, user_id, created_at) VALUES('Post prueba 2', 'Esto es una prueba', 3, current_timestamp);
INSERT INTO posts (title, description, user_id, created_at) VALUES('Post prueba 1', 'Esto es una prueba', 4, current_timestamp);
INSERT INTO posts (title, description, user_id, created_at) VALUES('Post prueba 2', 'Esto es una prueba', 4, current_timestamp);

INSERT INTO skills (name, created_at) VALUES ('Algorithms', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Analytics', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Android', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Applications', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Blogging', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Business', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Business Analysis', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Business Intelligence', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Business Storytelling', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Coaching', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Cloud Computing', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Communication', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Computer', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Consulting', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Content', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Content Management', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Content Marketing', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Content Strategy', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Data Analysis', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Data Analytics', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Data Engineering', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Data Mining', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Data Science', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Data Warehousing', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Database Administration', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Database Management', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Digital Marketing', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Digital Media', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Economics', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Editing', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Executive', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Event Planning', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Game Development', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Hadoop', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Health Care', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Hiring', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Hospitality', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Human Resources', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Information Management', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Information Security', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Information Technology', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('iPhone', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Java', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Job Specific Skills', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Legal', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Leadership ', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Mac', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Management', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Marketing', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Market Research', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Media Planning', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Microsoft Office Skills', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Mobile Apps', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Mobile Development', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Negotiation', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Network and Information Security', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Newsletters', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Online Marketing', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Presentation', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Project Management', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Public  Relations', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Recruiting', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Relationship Management', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Research', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Risk Management', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Search Engine Optimization ', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Social Media', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Social Media Management', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Social Networking', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Software', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Software Engineering', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Software Management', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Strategic Planning', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Strategy', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Tech Skills Listed by Job', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Tech Support', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Technical', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Training', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('UI / UX', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('User Testing', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Web Content', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Web Development', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Web Programming', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('WordPress', current_timestamp);
INSERT INTO skills (name, created_at) VALUES ('Writing', current_timestamp);

INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (1, 1);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (1, 2);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (1, 3);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (1, 4);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (2, 1);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (2, 2);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (2, 3);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (2, 4);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (3, 1);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (3, 2);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (3, 3);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (3, 4);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (4, 1);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (4, 2);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (4, 3);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (4, 4);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (5, 1);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (5, 2);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (5, 3);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (5, 4);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (6, 1);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (6, 2);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (6, 3);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (6, 4);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (7, 1);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (7, 2);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (7, 3);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (7, 4);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (8, 1);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (8, 2);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (8, 3);
INSERT INTO job_offer_skills (job_offer_id, skill_id) VALUES (8, 4);

INSERT INTO user_skills (user_id, skill_id) VALUES (1, 1);
INSERT INTO user_skills (user_id, skill_id) VALUES (1, 2);
INSERT INTO user_skills (user_id, skill_id) VALUES (1, 3);
INSERT INTO user_skills (user_id, skill_id) VALUES (1, 4);
INSERT INTO user_skills (user_id, skill_id) VALUES (2, 1);
INSERT INTO user_skills (user_id, skill_id) VALUES (2, 2);
INSERT INTO user_skills (user_id, skill_id) VALUES (2, 3);
INSERT INTO user_skills (user_id, skill_id) VALUES (2, 4);
INSERT INTO user_skills (user_id, skill_id) VALUES (3, 1);
INSERT INTO user_skills (user_id, skill_id) VALUES (3, 2);
INSERT INTO user_skills (user_id, skill_id) VALUES (3, 3);
INSERT INTO user_skills (user_id, skill_id) VALUES (3, 4);
INSERT INTO user_skills (user_id, skill_id) VALUES (4, 1);
INSERT INTO user_skills (user_id, skill_id) VALUES (4, 2);
INSERT INTO user_skills (user_id, skill_id) VALUES (4, 3);
INSERT INTO user_skills (user_id, skill_id) VALUES (4, 4);

INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (1, 3, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (1, 4, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (1, 5, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (1, 6, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (1, 7, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (1, 8, 'nada', current_timestamp);

INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (2, 1, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (2, 2, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (2, 5, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (2, 6, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (2, 7, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (2, 8, 'nada', current_timestamp);

INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (3, 3, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (3, 4, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (3, 1, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (3, 2, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (3, 7, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (3, 8, 'nada', current_timestamp);

INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (4, 3, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (4, 4, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (4, 5, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (4, 6, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (4, 1, 'nada', current_timestamp);
INSERT INTO job_applications (user_id, job_offer_id, description, created_at) VALUES (4, 2, 'nada', current_timestamp);
